FROM node:15
#    container_name: app
WORKDIR /app
#    tty: true

COPY ./app /app

ENV DB_HOST="mysql" \
    DB_PORT="3306" \
    DB_USER="fullcycle" \
    DB_PASSWORD="fullcycle_password" \
    DB_NAME="fullcycle"

#    networks:
#      - node-network
CMD ["npm", "start"]