version: '3'
services:

  app:
    image: node:15
    container_name: app
    working_dir: /app
    tty: true
    volumes:
      - ./app:/app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: fullcycle
      DB_PASSWORD: fullcycle_password
      DB_NAME: fullcycle
    networks:
      - node-network
    command: npm start


  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fullcycle
      MYSQL_USER: fullcycle
      MYSQL_PASSWORD: fullcycle_password
    networks:
      - node-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - node-network

  
networks:
  node-network:
    driver: bridge
  
