version: '3'
services:

  app:
    build:
      dockerfile: Dockerfile.app.prod
    container_name: app
    tty: true
    command: sh -c "npm install && npm start"
    volumes:
      - ./app:/app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: fullcycle
      DB_PASSWORD: fullcycle_password
      DB_NAME: fullcycle
    networks:
      - node-network
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      dockerfile: Dockerfile.db.prod
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fullcycle
      MYSQL_USER: fullcycle
      MYSQL_PASSWORD: fullcycle_password
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 3s

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - node-network

  
networks:
  node-network:
    driver: bridge
  
