FROM mysql:5.7
CMD ["--innodb-use-native-aio=0"] 

COPY ./mysql /var/lib/mysql

ENV MYSQL_ROOT_PASSWORD="root_password" \
    MYSQL_DATABASE="fullcycle" \
    MYSQL_USER="fullcycle" \
    MYSQL_PASSWORD="fullcycle_password"